/**
 * Custom Worker entry. OpenNext generates the Next.js server handler at
 * build time (.open-next/worker.js); this file re-exports it unchanged and
 * additionally exports the Workflow classes, which must be named exports of
 * the deployed Worker for the `workflows` bindings in wrangler.jsonc to
 * resolve. wrangler.jsonc points `main` here instead of at the generated
 * file.
 *
 * CRITICAL INVARIANT: nothing in this file may import app code at module
 * scope. Module-scope code runs at Worker __init, before any invocation
 * exists, so there are no env bindings and process.env is empty; app modules
 * that read configuration at import time (e.g. features/shared/supabase.ts
 * used to call createClient at top level) would crash the Worker at deploy
 * validation. That is why AnalyzePrWorkflow below is a thin shell: it first
 * hydrates process.env from this.env, and only then dynamically imports the
 * actual pipeline — the same order OpenNext itself guarantees for the Next
 * handler (it initializes the server inside the fetch handler, after env
 * hydration). Type-only imports are safe (erased at compile time).
 */

import { WorkflowEntrypoint } from 'cloudflare:workers';
import type { WorkflowEvent, WorkflowStep } from 'cloudflare:workers';
import type { AnalyzeJob } from './features/review-queue/workflow/steps';

/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore — generated by `opennextjs-cloudflare build`, absent from a clean checkout
export { default } from './.open-next/worker.js';
// @ts-ignore — same generated module (re-export any DO classes OpenNext emits)
export * from './.open-next/worker.js';

export class AnalyzePrWorkflow extends WorkflowEntrypoint<Record<string, unknown>, AnalyzeJob> {
  async run(event: WorkflowEvent<AnalyzeJob>, step: WorkflowStep): Promise<void> {
    // The app code reads configuration via process.env (populated by OpenNext
    // for request contexts, but NOT for Workflow invocations). Hydrate it
    // from the Workflow's own env bindings BEFORE importing any app module.
    for (const [key, value] of Object.entries(this.env)) {
      if (typeof value === 'string' && process.env[key] === undefined) {
        process.env[key] = value;
      }
    }

    const { runAnalyzePipeline } = await import(
      './features/review-queue/workflow/analyze-pr-workflow'
    );
    return runAnalyzePipeline(event, step);
  }
}
