/**
 * Custom Worker entry. OpenNext generates the Next.js server handler at
 * build time (.open-next/worker.js); this file re-exports it unchanged and
 * additionally exports the Workflow classes, which must be named exports of
 * the deployed Worker for the `workflows` bindings in wrangler.jsonc to
 * resolve. wrangler.jsonc points `main` here instead of at the generated
 * file.
 */

/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore — generated by `opennextjs-cloudflare build`, absent from a clean checkout
export { default } from './.open-next/worker.js';
// @ts-ignore — same generated module (re-export any DO classes OpenNext emits)
export * from './.open-next/worker.js';

export { AnalyzePrWorkflow } from './features/review-queue/workflow/analyze-pr-workflow';
